version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
      args:
        environment: local
      target: build
    container_name: application
    tty: true
    depends_on:
      - postgres
      - redis
    restart: on-failure
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - application-network

  nginx:
    image: nginx:1.25.2-alpine
    container_name: web-server
    restart: on-failure
    tty: true
    volumes:
      - .:/var/www
      - ./build/nginx/conf.d:/etc/nginx/conf.d
      - ./build/nginx/ngnix.conf:/etc/nginx/ngnix.conf
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - application-network

  postgres:
    image: postgres:15.4-bullseye
    container_name: database
    restart: on-failure
    tty: true
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=application_user
      - POSTGRES_PASSWORD=application_password
    volumes:
      - .:/var/www
      - database-storage:/var/lib/postgresql
    ports:
      -   "5432:5432"
    networks:
      - application-network

  redis:
    image: redis:7.0.11-bullseye
    container_name: cache
    restart: on-failure
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - cache-storage:/data
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  database-storage:
    driver: local
  cache-storage:
    driver: local
